apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  labels:
    app: zk
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 2181
    name: zkclient
  - port: 2888
    name: zkserver
  - port: 3888
    name: zkleader
  clusterIP: None
  selector:
    app: zk
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
  labels:
    app: zk
spec:
  serviceName: zk-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: zk
      annotations:
          scheduler.alpha.kubernetes.io/affinity: >
              {
                "podAntiAffinity": {
                  "requiredDuringSchedulingIgnoredDuringExecution": [{
                    "labelSelector": {
                      "matchExpressions": [{
                        "key": "app",
                        "operator": "In",
                        "values": ["zk"]
                      }]
                    },
                    "topologyKey": "kubernetes.io/hostname"
                  }]
                }
              }
    spec:
      containers:
      - name: zk
        imagePullPolicy: IfNotPresent
        image: engapa/zookeeper:3.4.10
        resources:
            requests:
              memory: 1Gi
              cpu: 1
            limits:
              memory: 1Gi
              cpu: 1
        ports:
        - containerPort: 2181
          name: zkclient
        - containerPort: 2888
          name: zkserver
        - containerPort: 3888
          name: zkleader
        env:
        - name: ZOO_REPLICAS
          value: "3"
        - name: JAVA_ZK_JVMFLAG
          value: "\"-Xmx1G -Xms1G\""
        command:
        - /bin/bash
        - -c
        - source zk_env.sh && zk_setup.sh && ./zkServer.sh start-foreground
        readinessProbe:
          exec:
            command:
            - zk_status.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - zk_status.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5